
Import('env')

# This won't work because we are building another exe,
# not concurring to build the previous exe
# env.Program('VPP', Glob('*.cpp') )

obj = env.Object( Glob('*.cpp') )
Return('obj')


