import os 

# Define a common build environment
env = Environment()

# Detect Qt version
QTDIR = '/Users/dtrimarchi/third_party/Qt/5.7'

# Clone Qt environment
qtEnv = env.Clone()

# Set QT5DIR and PKG_CONFIG_PATH
qtEnv['ENV']['PKG_CONFIG_PATH'] = os.path.join(QTDIR,'/Users/dtrimarchi/third_party/Qt/5.7/clang_64/lib/pkgconfig')

qtEnv['ENV']['PATH'] += ':/opt/local/bin'
print qtEnv['ENV']

qtEnv['QT5DIR'] = QTDIR
# Add qt5 tool
qtEnv.Tool("qt5")

qtEnv.EnableQt5Modules([
                    'QtCore'
                    ])

Export('env qtEnv')

env.Program('main', Glob('*.cpp'))
